language: python

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

cache:
  directories:
    - db

before_script: source .travis-scripts/download_db

# command to run tests
script:
  - nosetests -a \!wip
