#!/usr/bin/python

import shutil
from os import path
from expand import expand

recipe_literals = [
    'meatloaf',
    'chicken with rice',
    'pizza',
    'roasted duck with a side of carrots',
    'chocolate chip cookies',
    'pumpkin muffins',
    'black bean burritos with peas',
    '10-Minute Energizing Oatmeal',
    '10-Minute Huevos Rancheros',
    'Any Time Frittata',
    'Breakfast Bagel',
    'Granola with Fresh Fruit',
    'Healthy Breakfast Frittata',
    'Healthy Lifestyle Tea',
    'High Energy Breakfast Shake',
    'High Fiber Cereal',
    'Italian Tofu Frittata',
    'Mushroom, Tomato, Basil Frittata',
    'Perfect Oatmeal',
    'Poached Eggs Over Collard Greens & Shiitake Mushrooms',
    'Poached Eggs Over Sauteed Greens',
    'Poached Eggs over Spinach',
    'Poached Eggs over Spinach & Mushrooms',
    'Poached Eggs Over Spinach and Mushrooms 2',
    'Poached Huevos Rancheros',
    'Quinoa Power Breakfast',
    'Strawberry Smoothie',
    'Swiss Breakfast',
    'Yogurt with Fruit',
    'Salad Entrees',
    '10-Minute Fruit & Cheese Salad',
    '15-Minute Black Bean Salad',
    '15-Minute Greek Garbanzo Bean Salad',
    '15-Minute Halibut Salad',
    '15-Minute Shrimp and Avocado Salad',
    '15-Minute Turkey Chefs Salad',
    '5-Minute Greek Garbanzo Bean Salad',
    'Arugula Salad with Walnut Croutons (2)',
    'Asian Chicken Salad',
    'Broiled Salmon Salad',
    'Chinese Chicken Cabbage Salad',
    'Crispy Turkey Salad',
    'Dulse Cucumber Salad',
    'Dulse Cucumber Salad',
    'Garlic Shrimp Salad',
    'Greek Salad',
    'Ground Lamb Salad',
    'Healthy Caesar Salad',
    'Healthy Chefs Salad with Walnuts and French Dressing',
    'Healthy Chicken Caesar Salad',
    'Healthy Turkey Salad',
    'Healthy Veggie Salad',
    'Kidney Bean Salad with Mediterranean Dressing',
    'Lentil Salad',
    'Marinated Bean Salad',
    'Mediterranean Baby Spinach Salad',
    'Mediterranean Pasta Salad',
    'Mediterranean Tabouli Salad',
    'Mediterranean-Style Salad',
    'Mexican Cheese Salad',
    'Salad Nicoise',
    'Salmon, Cucumber, Dill Salad',
    'Seared Tuna Salad',
    'Shrimp Salad',
    'Soy Bean and Fennel Salad',
    'Tuna Salad Surprise',
    'Warm Spinach Salad with Tuna',
    'Soups',
    '5 Spice Onion Soup',
    '5-Minute Miso Soup with Dulse (sea vegetable)',
    'Barley Mushroom Soup',
    'Cajun Kidney Bean Chili',
    'Carrot Coconut Soup',
    'Golden Squash Soup',
    'Italian Navy Bean Soup with Rosemary',
    'Minestrone Surprise',
    'Oyster and Clam Chowder',
    'Red Kidney Bean Soup with Lime Yogurt',
    'Seafood Gazpacho',
    'Shiitake Mushroom Seaweed Soup',
    'Spicy Cabbage Soup',
    'Spicy Posole Soup',
    'Super Energy Kale Soup',
    'Turkey and Vegetable Chili Verde',
    'Zesty Mexican Soup',
    'Fish',
    '10-Minute Seared Tuna',
    '15-Minute Asian Tuna',
    '15-Minute Cod with Avocado Salsa',
    '15-Minute Maui-Style Cod',
    '15-Minute Salmon with Mint Salsa',
    '15-Minute Salmon with Mustard, Dill Sauce',
    '15-Minute Salmon with Tomato Salsa',
    '15-Minute Sauteed Fennel Salmon',
    '15-Minute Seared Tuna with Sage',
    '15-Minute Steamed Halibut with Bok Choy',
    '3-Minute Scallops',
    '5 Spice Salmon',
    '5-Minute "Quick Broiled" Salmon',
    '5-Minute Boiled Large Shrimp',
    'Baked Halibut with Herbs',
    'Baked Salmon & Walnut Patties With Red Bell Pepper Sauce',
    'Braised Cod with Celery',
    'Braised Salmon with Leeks',
    'Halibut with Ginger and Scallions',
    'Healthy Sauteed Seafood with Asparagus',
    'Lemon Fish with Puree of Sweet Peas',
    'Mediterranean Cod',
    'Mediterranean Cod with Tomatoes',
    'Miso Salmon',
    'Pasta with Clams',
    'Peanut Shrimp',
    'Poached Cod with Fennel and Cauliflower',
    'Poached Fish with Napa Cabbage',
    'Quick Broiled Halibut',
    'Quick Broiled Salmon with Ginger Mint Salsa',
    'Salmon in Citrus Sauce',
    'Salmon with Cucumber Chili Salad',
    'Salmon with Dill Sauce',
    'Salmon with Maple Dijon Glaze',
    'Salmon with Mustard',
    'Salmon with Mustard and Ginger',
    'Southwestern Cod Saute',
    'Southwestern Salmon & Black Beans',
    'Spicy Asian Shrimp',
    'Steamed Salmon and Asparagus with Mustard Dill Sauce',
    'Sweet and Sour Cod with Cabbage and Broccoli',
    'Thai-Style Cod with Seaweed',
    'Chicken and Turkey',
    '15-Minute Broiled Chicken Salad',
    '15-Minute Healthy Sauteed Chicken & Asparagus',
    '15-Minute Healthy Sauteed Chicken & Bok Choy',
    '15-Minute Sauteed Chicken Breasts with Mustard and Tarragon',
    '5-Spice Chicken in a Bowl',
    '7-Minute Quick Broiled Chicken',
    'Broiled Rosemary Chicken over Pureed Lentils and Swiss Chard',
    'Curried Chicken Over Spinach',
    'Fresh Herbed Chicken Breasts',
    'Healthy Sauteed Red Cabbage with Baked Chicken Breast',
    'Holiday Turkey with Rice Stuffing & Gravy with Fresh Herbs',
    'Quick Broiled Chicken Breast with Honey-Mustard Sauce',
    'Roast Turkey Breast with Chipotle Chili Sauce',
    'Sesame Braised Chicken & Cabbage',
    'Lean Meat',
    '10-Minute Rosemary Lamb Chops',
    'Indian Style Lamb with Sweet Potatoes',
    'Roast Leg of Lamb',
    'Rosemary "Quick Broiled" Lamb',
    'Vegetarian Entrees',
    '15-Minute Healthy Sauteed Asparagus and Tofu',
    '7-Minute "Healthy Steamed" Butternut Squash',
    'Asian-Flavored Broccoli with Tofu',
    'Black Bean Burrito, Indian Style',
    'Black Bean Chili',
    'Braised Kidney Beans & Sweet Potato',
    'Curried Lentils',
    'Curried Mustard Greens & Garbanzo Beans with Sweet Potatoes',
    'Fettuccini with Spinach Pesto',
    'Healthy Caesar Salad for Smart Menu',
    'Indian-Style Lentils',
    'Mediterranean Lentil Salad',
    'Miso Healthy Saute',
    'Moroccan Eggplant with Garbanzo Beans',
    'Polenta, Onion and Gorgonzola Pizza',
    'Primavera Verde',
    'Quick Black Bean Chili',
    'Spicy Black Bean Burrito',
    'Spicy Healthy Sauteed Tofu',
    'Spicy Vegetable Tart',
    'Steamed Butternut Squash with Almond Sauce',
    'Tan Tan Noodles',
    'Vegetarian Healthy Saute',
    'Warm Quinoa Salad',
    'Side Salad/Dressings',
    '5-Minute Cold Cucumber Salad 2',
    'Arugula Salad with Walnut Croutons',
    'Asparagus Salad',
    'Blue Cheese Dressing',
    'Cilantro Pesto with Pumpkin Seeds',
    'Cranberry Sauce',
    'Creamy Romaine Salad',
    'Cucumber Seaweed Salad',
    'Dijon Flaxseed Dressing',
    'Figs, Walnuts and Spinach Salad',
    'Fresh Tomato Salsa',
    'Fruit Salad with Papaya Seed Dressing',
    'Ginger Papaya Salsa',
    'Grape and Arugula Salad',
    'Grape and Melon Salad',
    'Grapefruit Arugula Salad',
    'Great Antipasto Salad',
    'Holiday Cranberry Relish',
    'Hummus with Crudites',
    'Kiwi Salad',
    'Mediterranean Dressing',
    'Mediterranean Dressing 2',
    'Mediterranean Tomato Salad',
    'Minted Garbanzo Bean Salad',
    'Napa Cabbage Salad',
    'Olive Tapenade',
    'Pineapple Salad with Ginger Syrup',
    'Romaine & Avocado Salad',
    'Super Carrot Raisin Salad',
    'Tomato Dandelion Salad',
    'Vegetable Appetizer 1',
    'Vegetable Appetizer 2',
    'Vegetable Appetizer 3',
    'Vegetable Appetizer 4',
    'Side Vegetables',
    '1-Minute Spinach',
    '15-Minute Beets',
    '3-Minute "Healthy Sauteed" Asparagus',
    '3-Minute "Healthy Sauteed" Green Peas',
    '3-Minute "Healthy Sauteed" Zucchini',
    '3-Minute Avocado Dip',
    '3-Minute Bok Choy',
    '3-Minute Swiss Chard',
    '4-Minute Broccoli with Feta Cheese and Kalamata Olives',
    '5-Minute "Quick Steamed" Carrots',
    '5-Minute "Quick Steamed" Corn',
    '5-Minute Brussels Sprouts',
    '5-Minute Collard Greens',
    '5-Minute Collard Greens with Sunflower Seeds',
    '5-Minute Green Beans',
    '5-Minute Healthy Sauteed Asparagus',
    '5-Minute Healthy Sauteed Cauliflower with Turmeric',
    '5-Minute Healthy Sauteed Red Cabbage',
    '5-Minute Healthy Sauteed Summer Squash',
    '5-Minute Kale',
    '5-Minute Kale with Sea Vegetables',
    '7-Minute "Healthy Sauteed" Shiitake Mushrooms',
    '7-Minute Healthy Sauteed Crimini Mushrooms',
    '7-Minute Healthy Sauteed Onions',
    '7-Minute Healthy Sauteed Red Bell Peppers',
    '7-Minute Sweet Potatoes',
    'Asian Mushroom Saute',
    'Asian Sauteed Cauliflower',
    'Baked Potato with Rosemary, Mushroom Sauce',
    'Beets with Fennel Yogurt Sauce',
    'Calabacitas (Mexican-flavored vegetable side dish)',
    'Carrot Cashew Pate',
    'Carrots with Honey Mustard Sauce',
    'Crimini Mushroom Saute',
    'Fennel Green Beans',
    'Fiesta Brown Rice Salad',
    'Garlic Dip',
    'Gingered Cabbage',
    'Golden Spinach and Sweet Potato Healthy Saute',
    'Healthy Creamed Corn',
    'Healthy Mashed Sweet Potatoes',
    'Kale with Hijiki',
    'Mediterranean Lima Beans',
    'Mediterranean Pinto Beans',
    'Minted Carrots with Pumpkin Seeds',
    'Minted Green Peas & Carrots',
    'Pinto Beans with Collard Greens',
    'Pureed Lima Beans with Rosemary Tomato Broth',
    'Pureed Navy Beans',
    'Pureed Sweet Peas',
    'Roasted Beets',
    'Sauteed Greens',
    'Sauteed Mushrooms with Green Peas',
    'Sauteed Vegetables with Cashews',
    'Seaweed Rice',
    'Smashed Potatoes with Garlic',
    'Steamed Butternut Squash with Red Chili Sauce',
    'Steamed Herbed Potatoes',
    'Steamed Mexican Corn on the Cob',
    'Steamed Vegetable Medley',
    'Sweet Potatoes with Ginger and Cinnamon',
    'Tahini and Crudites Appetizer',
    'Warm Asparagus Salad',
    'Wild Rice Pilaf',
    'Desserts',
    '10-Minute Apple Sundae',
    '10-Minute Apricot Bars',
    '10-Minute Fig and Fresh Apple Cobbler',
    '10-Minute Fresh Berry Dessert with Yogurt and Chocolate',
    '10-Minute Kiwi Mandala',
    '10-Minute Orange Treat',
    '10-Minute Peanut Bars',
    '10-Minute Strawberries with Chocolate Creme',
    '15-Minute Dark Chocolate Truffles',
    '5- Minute Blueberries with Yogurt',
    '5-Minute Fresh Plums in Sweet Sauce',
    '5-Minute Ginger Pineapple',
    '5-Minute Grapes in Honey-Lemon Sauce',
    '5-Minute Raspberry Almond Parfait',
    '5-Minute Watermelon Frappe',
    'Apple Treats',
    'Banana Colada',
    'Berries with Chocolate Sauce',
    'Blackberry Tart',
    'Blueberries with Cashew Sauce',
    'Blueberry Parfait',
    'Blueberry Peach Crisp',
    'Blueberry Trifle',
    'Cantaloupe with Lime and Mint',
    'Cranberry and Fresh Pear Cobbler',
    'Fresh Figs with Orange, Ginger Sauce',
    'Fresh Peaches with Blueberries & Yogurt',
    'Ginger Yogurt with Fruit',
    'Grapefruit Sunrise',
    'No-Bake Apple Walnut Tart',
    'Orange and Coconut Treat',
    'Orange, Pineapple, Papaya Salad',
    'Papaya with Lime',
    'Sesame Bar',
    'Tropical Banana Treat',
    'Meatless Recipes',
    'Breakfast',
    '10-Minute Energizing Oatmeal',
    '10-Minute Huevos Rancheros',
    'Any Time Frittata',
    'Breakfast Bagel',
    'Granola with Fresh Fruit',
    'Healthy Lifestyle Tea',
    'High Energy Breakfast Shake',
    'Italian Tofu Frittata',
    'Mushroom, Tomato, Basil Frittata',
    'Perfect Oatmeal',
    'Poached Eggs Over Collard Greens & Shiitake Mushrooms',
    'Poached Eggs Over Sauteed Greens',
    'Poached Eggs over Spinach',
    'Poached Eggs over Spinach & Mushrooms',
    'Poached Eggs Over Spinach and Mushrooms 2',
    'Poached Huevos Rancheros',
    'Quinoa Power Breakfast',
    'Strawberry Smoothie',
    'Swiss Breakfast',
    'Yogurt with Fruit',
    'Salad Entrees',
    '10-Minute Fruit & Cheese Salad',
    '15-Minute Black Bean Salad',
    '15-Minute Greek Garbanzo Bean Salad',
    '5-Minute Greek Garbanzo Bean Salad',
    'Dulse Cucumber Salad',
    'Dulse Cucumber Salad',
    'Greek Salad',
    'Healthy Caesar Salad',
    'Healthy Veggie Salad',
    'Kidney Bean Salad with Mediterranean Dressing',
    'Lentil Salad',
    'Marinated Bean Salad',
    'Mediterranean Baby Spinach Salad',
    'Mediterranean Pasta Salad',
    'Mediterranean Tabouli Salad',
    'Mediterranean-Style Salad',
    'Mexican Cheese Salad',
    'Soy Bean and Fennel Salad',
    'Soups',
    '5 Spice Onion Soup',
    '5-Minute Miso Soup with Dulse (sea vegetable)',
    'Barley Mushroom Soup',
    'Cajun Kidney Bean Chili',
    'Carrot Coconut Soup',
    'Golden Squash Soup',
    'Italian Navy Bean Soup with Rosemary',
    'Minestrone Surprise',
    'Red Kidney Bean Soup with Lime Yogurt',
    'Shiitake Mushroom Seaweed Soup',
    'Spicy Cabbage Soup',
    'Spicy Posole Soup',
    'Super Energy Kale Soup',
    'Zesty Mexican Soup',
    'Vegetarian Entrees',
    '15-Minute Healthy Sauteed Asparagus and Tofu',
    'Asian-Flavored Broccoli with Tofu',
    'Black Bean Burrito, Indian Style',
    'Black Bean Chili',
    'Braised Kidney Beans & Sweet Potato',
    'Curried Lentils',
    'Curried Mustard Greens & Garbanzo Beans with Sweet Potatoes',
    'Fettuccini with Spinach Pesto',
    'Healthy Caesar Salad for Smart Menu',
    'Indian-Style Lentils',
    'Mediterranean Lentil Salad',
    'Miso Healthy Saute',
    'Moroccan Eggplant with Garbanzo Beans',
    'Polenta, Onion and Gorgonzola Pizza',
    'Primavera Verde',
    'Quick Black Bean Chili',
    'Spicy Black Bean Burrito',
    'Spicy Healthy Sauteed Tofu',
    'Steamed Butternut Squash with Almond Sauce',
    'Tan Tan Noodles',
    'Vegetarian Healthy Saute',
    'Warm Quinoa Salad',
    'Side Salad/Dressings',
    '5-Minute Cold Cucumber Salad 2',
    'Arugula Salad with Walnut Croutons',
    'Asparagus Salad',
    'Blue Cheese Dressing',
    'Cilantro Pesto with Pumpkin Seeds',
    'Cranberry Sauce',
    'Creamy Romaine Salad',
    'Cucumber Seaweed Salad',
    'Dijon Flaxseed Dressing',
    'Figs, Walnuts and Spinach Salad',
    'Fresh Tomato Salsa',
    'Fruit Salad with Papaya Seed Dressing',
    'Ginger Papaya Salsa',
    'Grape and Arugula Salad',
    'Grape and Melon Salad',
    'Grapefruit Arugula Salad',
    'Great Antipasto Salad',
    'Holiday Cranberry Relish',
    'Hummus with Crudites',
    'Kiwi Salad',
    'Mediterranean Dressing',
    'Mediterranean Dressing 2',
    'Mediterranean Tomato Salad',
    'Minted Garbanzo Bean Salad',
    'Napa Cabbage Salad',
    'Olive Tapenade',
    'Pineapple Salad with Ginger Syrup',
    'Romaine & Avocado Salad',
    'Super Carrot Raisin Salad',
    'Tomato Dandelion Salad',
    'Vegetable Appetizer 1',
    'Vegetable Appetizer 2',
    'Vegetable Appetizer 3',
    'Vegetable Appetizer 4',
    'Side Vegetables',
    '1-Minute Spinach',
    '15-Minute Beets',
    '3-Minute "Healthy Sauteed" Asparagus',
    '3-Minute "Healthy Sauteed" Green Peas',
    '3-Minute "Healthy Sauteed" Zucchini',
    '3-Minute Avocado Dip',
    '3-Minute Bok Choy',
    '3-Minute Swiss Chard',
    '4-Minute Broccoli with Feta Cheese and Kalamata Olives',
    '5-Minute "Quick Steamed" Carrots',
    '5-Minute "Quick Steamed" Corn',
    '5-Minute Brussels Sprouts',
    '5-Minute Collard Greens',
    '5-Minute Collard Greens with Sunflower Seeds',
    '5-Minute Green Beans',
    '5-Minute Healthy Sauteed Asparagus',
    '5-Minute Healthy Sauteed Cauliflower with Turmeric',
    '5-Minute Healthy Sauteed Red Cabbage',
    '5-Minute Healthy Sauteed Summer Squash',
    '5-Minute Kale',
    '5-Minute Kale with Sea Vegetables',
    '7-Minute "Healthy Sauteed" Shiitake Mushrooms',
    '7-Minute Healthy Sauteed Crimini Mushrooms',
    '7-Minute Healthy Sauteed Onions',
    '7-Minute Healthy Sauteed Red Bell Peppers',
    '7-Minute Sweet Potatoes',
    'Asian Mushroom Saute',
    'Asian Sauteed Cauliflower',
    'Baked Potato with Rosemary, Mushroom Sauce',
    'Beets with Fennel Yogurt Sauce',
    'Calabacitas (Mexican-flavored vegetable side dish)',
    'Carrot Cashew Pate',
    'Carrots with Honey Mustard Sauce',
    'Crimini Mushroom Saute',
    'Fennel Green Beans',
    'Fiesta Brown Rice Salad',
    'Garlic Dip',
    'Gingered Cabbage',
    'Golden Spinach and Sweet Potato Healthy Saute',
    'Healthy Creamed Corn',
    'Healthy Mashed Sweet Potatoes',
    'Kale with Hijiki',
    'Mediterranean Lima Beans',
    'Mediterranean Pinto Beans',
    'Minted Carrots with Pumpkin Seeds',
    'Minted Green Peas & Carrots',
    'Pinto Beans with Collard Greens',
    'Pureed Lima Beans with Rosemary Tomato Broth',
    'Pureed Navy Beans',
    'Pureed Sweet Peas',
    'Roasted Beets',
    'Sauteed Greens',
    'Sauteed Mushrooms with Green Peas',
    'Sauteed Vegetables with Cashews',
    'Seaweed Rice',
    'Steamed Butternut Squash with Red Chili Sauce',
    'Steamed Herbed Potatoes',
    'Steamed Mexican Corn on the Cob',
    'Steamed Vegetable Medley',
    'Sweet Potatoes with Ginger and Cinnamon',
    'Tahini and Crudites Appetizer',
    'Warm Asparagus Salad',
    'Wild Rice Pilaf',
    '10-Minute Apple Sundae',
    '10-Minute Apricot Bars',
    '10-Minute Fig and Fresh Apple Cobbler',
    '10-Minute Fresh Berry Dessert with Yogurt and Chocolate',
    '10-Minute Kiwi Mandala',
    '10-Minute Orange Treat',
    '10-Minute Peanut Bars',
    '10-Minute Strawberries with Chocolate Creme',
    '15-Minute Dark Chocolate Truffles',
    '5- Minute Blueberries with Yogurt',
    '5-Minute Fresh Plums in Sweet Sauce',
    '5-Minute Ginger Pineapple',
    '5-Minute Grapes in Honey-Lemon Sauce',
    '5-Minute Raspberry Almond Parfait',
    '5-Minute Watermelon Frappe',
    'Apple Treats',
    'Banana Colada',
    'Berries with Chocolate Sauce',
    'Blackberry Tart',
    'Blueberries with Cashew Sauce',
    'Blueberry Parfait',
    'Blueberry Peach Crisp',
    'Blueberry Trifle',
    'Cranberry and Fresh Pear Cobbler',
    'Fresh Figs with Orange, Ginger Sauce',
    'Fresh Peaches with Blueberries & Yogurt',
    'Ginger Yogurt with Fruit',
    'Grapefruit Sunrise',
    'No-Bake Apple Walnut Tart',
    'Orange and Coconut Treat',
    'Orange, Pineapple, Papaya Salad',
    'Papaya with Lime',
    'Tropical Banana Treat',
]

ways_to_cook = [
    'bake',
    'roast',
    'broil',
    'puree',
    'braise',
    'caramelize',
    'deep fry',
    'grill',
    'juice',
    'marinate',
    'pickle',
    'steam',
    'sear',
    'boil',
    'poach',
    'fry',
]

words_for_cook = [
    'cook',
    'make',
    'create',
]

intents = [
    {
        'name': 'StartNewRecipeIntent',
        'samples': [
            [['Find me a recipe for', 'Let\'s make'], ' {', recipe_literals, '|RecipeName}'],
            [['How do I', 'Show me how to', 'Help me'], ' ',  words_for_cook, ' {', recipe_literals, '|RecipeName}'],
            [['show', 'tell'], ' me how to ' , words_for_cook,  ' {', recipe_literals, '|RecipeName}'],
            ['How is {', recipe_literals ,'|RecipeName} ' , words_for_cook],
        ]
    }
]


if __name__=="__main__":
    # backup a copy first
    if path.isfile('SampleUtterances.txt'):
        shutil.copy2('SampleUtterances.txt', 'SampleUtterances.txt.bak')

    f = open('SampleUtterances.txt','w')

    for intent in intents:
        for sample in intent['samples']:
            variants = expand(sample)
            for variant in variants:
                variant_str = "".join(variant)
                f.write(intent['name'] + ' ' + variant_str + '\n')

    f.close()

