#!/bin/bash
set -e

if [ ! -d "db" ]; then
  mkdir db;
  wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O dynamodb_local_latest.tar.gz;
  tar -xf dynamodb_local_latest.tar.gz -C db
fi

cd db
ls
java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
